const bank=[['예?','예?','Q'],['엄.','엄','W'],['아뇨아뇨아뇨','아뇨 아뇨 아뇨','E'],['줴줴이야~','줴줴이야','R'],['요이~','요이','A'],['티~~~원','티 원','S'],['드가자','드가자','D'],['기미히끼잉','기미히끼잉','F'],['진~지?','진지?','Z'],['지~랄','지랄','X'],['야르~','야르','C'],['아 예?','아 예?','V']];
const samples=new Map(),players=new Set(),timers=new Set();let sequence=Array(8).fill(-1),loop=null,cursor=0,flashTimers=new Map();
const status=document.querySelector('#status'),volume=document.querySelector('#volume'),bpm=document.querySelector('#bpm'),pitch=document.querySelector('#pitch');
function updatePitch(){document.querySelector('#pitch-value').textContent=Number(pitch.value).toFixed(2)+'×'}
pitch.addEventListener('input',updatePitch);document.querySelector('#pitch-reset').onclick=()=>{pitch.value='1';updatePitch()};
function notify(text){status.textContent=text}
function flash(i){const el=document.querySelectorAll('.pad')[i];clearTimeout(flashTimers.get(i));el.classList.add('active');flashTimers.set(i,setTimeout(()=>el.classList.remove('active'),180))}
function trigger(i){flash(i);if(samples.has(i)){const a=new Audio(samples.get(i));a.volume=Number(volume.value);a.preservesPitch=false;a.playbackRate=Number(pitch.value);players.add(a);a.onended=()=>players.delete(a);a.onerror=()=>{players.delete(a);notify('음성 파일을 재생할 수 없어. 다른 파일을 올려 봐.')};a.play().catch(()=>{players.delete(a);notify('재생하지 못했어. 패드를 직접 눌러 다시 시도해 봐.')});return}
if(!('speechSynthesis' in window)){notify('이 브라우저는 합성음성을 지원하지 않아. 패드에 음성 파일을 올려 줘.');return}
const utterance=new SpeechSynthesisUtterance(bank[i][1]);utterance.lang='ko-KR';utterance.volume=Number(volume.value);utterance.rate=i===2?1.65:1.15;utterance.pitch=Number(pitch.value);const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('ko'));if(voice)utterance.voice=voice;speechSynthesis.cancel();speechSynthesis.speak(utterance);notify(bank[i][0]+' · 합성음성 재생')}
bank.forEach(([name,text,key],i)=>{const wrap=document.createElement('div');wrap.className='pad-wrap';const pad=document.createElement('button');pad.className='pad';pad.setAttribute('aria-label',name+' 재생, 단축키 '+key);pad.innerHTML=`<span class="pad-top"><span>${String(i+1).padStart(2,'0')}</span><span class="key">${key}</span></span><strong>${name}</strong><span class="source">TTS</span>`;pad.onclick=()=>trigger(i);const upload=document.createElement('button');upload.className='upload';upload.textContent='+ 음성';upload.setAttribute('aria-label',name+' 음성 파일 업로드');const input=document.createElement('input');input.type='file';input.accept='audio/*';input.hidden=true;upload.onclick=()=>input.click();input.onchange=()=>{const file=input.files[0];if(!file)return;if(!file.type.startsWith('audio/')&&!/\.(mp3|wav|ogg|m4a|aac|flac|webm)$/i.test(file.name)){notify('음성 파일을 선택해 줘.');return}if(samples.has(i))URL.revokeObjectURL(samples.get(i));samples.set(i,URL.createObjectURL(file));pad.querySelector('.source').textContent='SAMPLE';notify(name+' 음성을 교체했어. 파일은 서버에 전송되지 않고 새로고침하면 초기화돼.')};wrap.append(pad,upload,input);document.querySelector('#pads').append(wrap)});
function renderSteps(){document.querySelectorAll('.step').forEach((el,i)=>{el.innerHTML=`<span>0${i+1}</span>${sequence[i]<0?'＋':bank[sequence[i]][0]}`;el.classList.toggle('filled',sequence[i]>=0)})}
for(let i=0;i<8;i++){const el=document.createElement('button');el.className='step';el.setAttribute('aria-label',(i+1)+'번째 박자 소리 변경');el.onclick=()=>{sequence[i]=(sequence[i]+2)%(bank.length+1)-1;renderSteps()};document.querySelector('#steps').append(el)}renderSteps();
function stopLoop(){clearTimeout(loop);loop=null;document.querySelector('#play').textContent='▶ 루프 시작';document.querySelectorAll('.step').forEach(el=>el.classList.remove('current'))}
function stopAll(){stopLoop();if('speechSynthesis' in window)speechSynthesis.cancel();players.forEach(a=>{a.pause();a.currentTime=0});players.clear();notify('모든 소리를 멈췄어.')}
function tick(){document.querySelectorAll('.step').forEach((el,i)=>el.classList.toggle('current',i===cursor));if(sequence[cursor]>=0)trigger(sequence[cursor]);cursor=(cursor+1)%8;loop=setTimeout(tick,60000/Math.max(60,Math.min(180,Number(bpm.value)||100)))}
document.querySelector('#play').onclick=()=>{if(loop!==null){stopLoop();return}if(sequence.every(i=>i<0)){sequence=[0,1,-1,2,3,-1,4,6];renderSteps()}cursor=0;document.querySelector('#play').textContent='■ 루프 정지';tick()};document.querySelector('#clear').onclick=()=>{stopAll();sequence.fill(-1);renderSteps()};document.querySelector('#stop').onclick=stopAll;
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(e.key==='Escape'){stopAll();return}const i=bank.findIndex(x=>x[2].toLowerCase()===e.key.toLowerCase());if(i>=0){e.preventDefault();trigger(i)}});window.addEventListener('pagehide',stopAll);
